title: Fosco Loregian
subtitle: "逢佛殺佛"
baseurl: ""
url: "https://tetrapharmakon.github.io"
email: fosco.loregian@gmail.com
twitter_username: tetrapharmakon
github_username: tetrapharmakon

favicon: assets/favicon.png

js:
    early:
    late:
        - js/jquery.min.js
        - js/fchoue.js
        - js/bibtex-copy-button.js

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      nav_active: Blog
      permalink: /blog/:year/:month/:day/:title/

keywords: category theory, mathematics, research
description: Personal academic website of Fosco Loregian, mathematician working in category theory.

collections:
  talks:
  organized:
  dida:
  misc:
  automata:
  coends:
  homotopy:
  miscpaper:
  petri:
  twocat:
  refcards:

sass:
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - plugins
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
