# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:            Mathetic
tagline:          Compelling tagline
url:              http://paolobrasolin.github.io/
paginate:         1
baseurl:          http://paolobrasolin.github.io/
author:
  name:           Paolo Brasolin
  url:            https://plus.google.com/+PaoloBrasolin
  email:          paolo.brasolin@gmail.com

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"