# Information
title:               paolobrasolin.github.io
author:
  name:              Paolo Brasolin
  url:               https://plus.google.com/+PaoloBrasolin
  email:             paolo.brasolin@gmail.com

# Conversion
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "strikethrough", "smart"]

# Output
permalink: /epistolae/:title/

# Layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"