# Custom
title:               paolobrasolin.github.io
author:
  name:              Paolo Brasolin
  url:               https://plus.google.com/+PaoloBrasolin
  email:             paolo.brasolin@gmail.com

# Filtering Content
# show_drafts: null
# limit_posts: 0
# future:      true
# unpublished: false

# Conversion
# markdown:    kramdown
# highlighter: pygments
# excerpt_separator: "\n\n"

# Serving
baseurl: http://paolobrasolin.github.io/

# Backwards-compatibility
relative_permalinks: true

# Outputting
permalink: pretty

# Markdown flavouring
#markdown: redcarpet
markdown: kramdown
#redcarpet:
#  extensions: ["strikethrough"]

# Defaults
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "pages"
    values:
      layout: "page"
