# Custom
title:               paolobrasolin.github.io
author:
  name:              Paolo Brasolin
  url:               https://plus.google.com/+PaoloBrasolin
  email:             paolo.brasolin@gmail.com

# Filtering Content
# show_drafts: null
# limit_posts: 0
# future:      true
# unpublished: false

# Conversion
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "strikethrough"]
#kramdown:
#  input: GFM
#highlighter: null
# excerpt_separator: "\n\n"

# Serving
#baseurl: http://paolobrasolin.github.io/

# Backwards-compatibility
relative_permalinks: true

# Outputting
permalink: /epistolae/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
