# This file is autogenerated by the flake.nix file, do not edit
source "https://rubygems.org"

# Gems dependencies to be installed
gem "activesupport", "~> 7.2.3.1"
gem "jekyll", "~> 4.3"
gem "minima", "~> 2.5"
gem "webrick", "~> 1.8"

# Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
end

